import { Neuton } from 'next/font/google';

const neuton = Neuton({
	weight: ['300', '400', '700'],
	style: 'normal',
	display: 'swap',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className={neuton.className}>
			<body>{children}</body>
		</html>
	);
}
