import { Neuton } from 'next/font/google';
import '@/styles/global.css';
import Header from '@/components/header';

const neuton = Neuton({
	weight: ['300', '400', '700'],
	style: 'normal',
	display: 'swap',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' className={neuton.className}>
			<body className='bg-[#F0EEE2] text-[#272935]'>
				<Header />
				{children}
			</body>
		</html>
	);
}
